### ISSUE TITLE
Tap doesn't work

### ISSUE THREAD

**Issue by Basilisk2305** [kkorouei/ARDominoes#1]
I cannot draw dominoes no matter what. I swipe, tap and interact with the screen, but nothing's working.

**Comment by kkorouei** [comment]
When the app starts, point your phone at the ground and move it around for a couple seconds so a surface can be detected. Then you can start drawing dominoes. (Make sure to restart the app each time)

**Comment by Basilisk2305** [comment]
I have often left the app for a minute, rotating my phone so the app gets a good layout, but nothing works still.

**Comment by kkorouei** [comment]
Make sure you are in a well lit room and that the surface you are tracking has enough detail.
Try commenting out line 145 ( plane.firstMaterial?.colorBufferWriteMask = .init(rawValue: 0) )
This will make any detected planes visible and therefore you will see if the surface has been detected.
